version: 0.2
env:
  variables:
    GOOS: "linux"
    S3_BUCKET: "harmony-server-bucket"
    PACKAGE: "github.com/mchozhang/harmony-server"

phases:
  install:
    commands:
      # AWS Codebuild Go images use /go for the $GOPATH so let's copy our
      # application source code into that directory structure.
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"

      # print all environment variables (handy for AWS CodeBuild logs)
      - env

      # install dep
#      - go get -u github.com/golang/dep/cmd/dep
      - go get -u github.com/aws/aws-lambda-go
      - go get -u github.com/aws/aws-sdk-go
      - go get -u github.com/graphql-go/graphql

      # install dependencies
#      - dep ensure -v
  pre_build:
    commands:
      # no tests at the moment
      - echo 'prebuild phase'
  build:
    commands:
      # Build project using AWS SAM
      - go build -o main ./handler/main.go
      # Use AWS SAM to package the application
      - sam package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml
