# basic serverless config file,
# if the cloudformation template is used to deploy,
# then this config is not applied

service: harmony-server
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: ap-southeast-2
  environment:
    TABLE_NAME: ${self:service}-levels
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:*"

package:
  exclude:
    - ./**
    - ./*.zip
  include:
    - ./bin/**

functions:
  handler:
    handler: bin/handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
